"""Live FAISS + OpenAI implementation of the single hiring agent.

Design notes
------------
* All case materials (company context, role description, screening policy, candidate CV)
  come from ``case.json`` -- no uploaded CV, no dynamic candidate text.
* The final recommendation is fixed by protocol in ``case.json["fixed_assessment"]["recommendation"]``.
  The LLM generates only the evidence-grounded narrative fields.
* Multi-section citations are supported: ``role_citations`` and ``policy_citations`` are lists,
  enabling subsection-level IDs such as ``role_section_5_2`` or ``policy_section_7_3``.
* All fixed materials are indexed together in a single FAISS store; no separate candidate store.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
import re
from typing import Iterable

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from openai import OpenAI
from pydantic import BaseModel

from .config import load_project_openai_config  # noqa: F401 -- re-exported for back-compat
from .engine import DEFAULT_CASE_PATH, Assessment, Evidence, HiringRAGAssistant


GENERATION_MODEL = "gpt-4o-mini-2024-07-18"
EMBEDDING_MODEL = "text-embedding-3-small"

DEFAULT_VECTOR_STORE_DIR = (
    Path(__file__).resolve().parents[2] / "study" / "vector_store" / "company_knowledge"
)


class GroundedBasis(BaseModel):
    """Evidence-grounded narrative fields generated by the LLM.

    The recommendation itself is NOT generated here -- it is fixed in case.json.
    Multi-section citations use lists so that subsection-level anchors can be
    embedded inline in the conversational recommendation text.
    """

    candidate_evidence: str
    company_basis: str
    company_citation: str
    uncertain_capability: str
    role_basis: str
    role_citations: list[str]    # e.g. ["Section 5.2", "Section 6.1"]
    policy_basis: str
    policy_citations: list[str]  # e.g. ["Section 7.3", "Section 9.1"]
    cv_citations: list[str]      # evidence_id values of retrieved CV sections, e.g. ["cv_1"]


class OpenAIFAISSHiringAgent(HiringRAGAssistant):
    """One agent backed by a persisted FAISS index over all fixed case materials.

    Company context, role description, screening policy, and candidate CV sections
    are all indexed together.  There is no uploaded CV and no separate candidate store.
    The recommendation is fixed from ``case.json``; the LLM generates evidence fields only.
    """

    def __init__(
        self,
        case_path: Path | str = DEFAULT_CASE_PATH,
        *,
        persist_directory: Path | str = DEFAULT_VECTOR_STORE_DIR,
        generation_model: str = GENERATION_MODEL,
        embedding_model: str = EMBEDDING_MODEL,
        client: OpenAI | None = None,
        embeddings: object | None = None,
    ) -> None:
        super().__init__(case_path)
        self.generation_model = generation_model
        self.embedding_model = embedding_model
        self.persist_directory = Path(persist_directory)
        self._client = client or OpenAI()
        self._embeddings = embeddings or OpenAIEmbeddings(model=embedding_model)
        self._internal_store = self._build_internal_store()

    # -- Vector store ----------------------------------------------------------

    def _documents_for(self, evidence_items: Iterable[Evidence]) -> list[Document]:
        documents = [
            Document(
                page_content=f"{item.heading}\n{item.text}",
                metadata={
                    "evidence_id": item.evidence_id,
                    "document": item.document,
                    "heading": item.heading,
                    "text": item.text,
                },
            )
            for item in evidence_items
        ]
        return RecursiveCharacterTextSplitter(
            chunk_size=700, chunk_overlap=50
        ).split_documents(documents)

    def _build_internal_store(self) -> FAISS:
        """Embed all fixed case materials into a single FAISS index."""
        chunks = self._documents_for(self.documents)
        digest_source = "\n".join(item.page_content for item in chunks).encode("utf-8")
        digest = hashlib.sha256(digest_source).hexdigest()[:12]
        index_dir = self.persist_directory / f"internal_{digest}"
        if index_dir.exists():
            return FAISS.load_local(
                str(index_dir), self._embeddings, allow_dangerous_deserialization=True
            )
        self.persist_directory.mkdir(parents=True, exist_ok=True)
        store = FAISS.from_documents(chunks, self._embeddings)
        store.save_local(str(index_dir))
        return store

    @staticmethod
    def _to_evidence(results: list[tuple[Document, float]]) -> tuple[Evidence, ...]:
        evidence: list[Evidence] = []
        seen: set[str] = set()
        for document, score in results:
            evidence_id = str(document.metadata["evidence_id"])
            if evidence_id in seen:
                continue
            seen.add(evidence_id)
            evidence.append(
                Evidence(
                    evidence_id=evidence_id,
                    document=str(document.metadata["document"]),
                    heading=str(document.metadata["heading"]),
                    text=str(document.metadata["text"]),
                    score=round(float(score), 3),
                )
            )
        return tuple(evidence)

    def retrieve(self, query: str, top_k: int = 12) -> tuple[Evidence, ...]:
        results = self._internal_store.similarity_search_with_score(query, k=top_k)
        return self._to_evidence(results)

    # -- Assessment ------------------------------------------------------------

    def assess(self, user_focus: str = "") -> Assessment:
        """Retrieve evidence, ground via LLM, and apply the fixed protocol recommendation."""
        rule = self.case["fixed_assessment"]
        # Recommendation is fixed by experimental protocol -- not chosen by the LLM.
        fixed_recommendation = rule["recommendation"]
        retrieved = self.retrieve(rule["retrieval_query"], top_k=12)
        grounded = self._ground_recommendation(retrieved, user_focus=user_focus)
        self._validate_company_citation(grounded.company_citation, retrieved)
        self._validate_role_citations(grounded.role_citations, retrieved)
        self._validate_policy_citations(grounded.policy_citations, retrieved)
        basis = grounded.model_dump()
        # Flatten list citations to a normalised string for engine.py response templates.
        basis["role_citation"] = self._normalize_section_citations(grounded.role_citations)
        basis["policy_citation"] = self._normalize_section_citations(grounded.policy_citations)
        return Assessment(
            recommendation=fixed_recommendation,
            retrieved=retrieved,
            supporting=retrieved,
            caution=(),
            generated_basis=basis,
            retrieval_backend=f"faiss_all_materials:{self.embedding_model}",
            generation_backend=f"openai_responses:{self.generation_model}",
        )

    # -- Citation validation ---------------------------------------------------

    @staticmethod
    def _validate_company_citation(citation: str, retrieved: tuple[Evidence, ...]) -> None:
        if not citation.strip():
            raise ValueError("The generated company citation must not be empty.")
        if not any(item.evidence_id.startswith("company_") for item in retrieved):
            raise ValueError("No company-context evidence was retrieved.")

    @staticmethod
    def _normalize_section_citations(citations: list[str]) -> str:
        """Deduplicate and join section references from a citation list."""
        sections: list[str] = []
        seen: set[str] = set()
        for citation in citations:
            for match in re.findall(r"Section\s+\d+(?:\.\d+)?", citation):
                if match not in seen:
                    seen.add(match)
                    sections.append(match)
        return ", ".join(sections)

    @staticmethod
    def _validate_role_citations(citations: list[str], retrieved: tuple[Evidence, ...]) -> None:
        """Validate each role section citation against retrieved evidence IDs.

        Accepts both major-section IDs (``role_section_5``) and subsection IDs
        (``role_section_5_2``), so that responses citing Section 5.2 are valid
        when either ``role_section_5`` or ``role_section_5_2`` was retrieved.
        """
        if not citations:
            raise ValueError("The generated output must include at least one role citation.")
        retrieved_ids = {item.evidence_id for item in retrieved}
        for citation in citations:
            numbers = re.findall(r"Section\s+(\d+(?:\.\d+)?)", citation)
            if not numbers:
                raise ValueError(f"Role citation contains no section number: {citation!r}")
            for num in numbers:
                subsection_id = f"role_section_{num.replace('.', '_')}"
                parent_id = f"role_section_{num.split('.')[0]}"
                if subsection_id not in retrieved_ids and parent_id not in retrieved_ids:
                    raise ValueError(
                        f"Role citation {citation!r} not found in retrieved evidence "
                        f"(checked {subsection_id!r} and {parent_id!r})."
                    )

    @staticmethod
    def _validate_policy_citations(citations: list[str], retrieved: tuple[Evidence, ...]) -> None:
        """Validate each policy section citation against retrieved evidence IDs.

        Accepts both ``policy_section_7`` and ``policy_section_7_3``.
        """
        if not citations:
            raise ValueError("The generated output must include at least one policy citation.")
        retrieved_ids = {item.evidence_id for item in retrieved}
        for citation in citations:
            numbers = re.findall(r"Section\s+(\d+(?:\.\d+)?)", citation)
            if not numbers:
                raise ValueError(f"Policy citation contains no section number: {citation!r}")
            for num in numbers:
                subsection_id = f"policy_section_{num.replace('.', '_')}"
                parent_id = f"policy_section_{num.split('.')[0]}"
                if subsection_id not in retrieved_ids and parent_id not in retrieved_ids:
                    raise ValueError(
                        f"Policy citation {citation!r} not found in retrieved evidence "
                        f"(checked {subsection_id!r} and {parent_id!r})."
                    )

    # -- LLM grounding --------------------------------------------------------

    def _ground_recommendation(
        self, retrieved: tuple[Evidence, ...], user_focus: str = ""
    ) -> GroundedBasis:
        context = "\n\n".join(
            f"[{item.evidence_id}] {item.document} / {item.heading}: {item.text}"
            for item in retrieved
        )
        focus_clause = (
            f"\n\nThe recruiter has asked you to pay particular attention to the following "
            f"priorities when forming the evidence summary: {user_focus.strip()}"
            if user_focus.strip() else ""
        )
        response = self._client.responses.parse(
            model=self.generation_model,
            input=[
                {
                    "role": "system",
                    "content": (
                        "You are a bounded recruitment screening assistant in a "
                        "controlled HAI experiment. Use only the retrieved evidence provided. "
                        "Your task is to generate an evidence-grounded narrative for the screening "
                        "recommendation. Do NOT choose the recommendation -- that is fixed externally. "
                        "Assess the candidate CV provided in the fixed case materials against "
                        "the role description requirements and the screening policy rules. "
                        "Use retrieved company context to ground company_basis only. "
                        "For role_citations, provide a list of retrieved section references "
                        "such as [\"Section 5.2\", \"Section 6.1\"]. "
                        "For policy_citations, provide a list of retrieved section references "
                        "such as [\"Section 7.3\", \"Section 9.1\"]. "
                        "For cv_citations, list the evidence_id values of retrieved candidate "
                        "CV sections used, such as [\"cv_1\", \"cv_2\"]. "
                        "Where the recruiter has stated priorities, address those dimensions "
                        "explicitly in candidate_evidence and role_basis -- but do not alter the "
                        "overall framing of the recommendation. "
                        "Do not infer protected traits or unstated experience."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "Generate grounded evidence fields for the candidate "
                        f"using these retrieved materials:\n\n{context}{focus_clause}"
                    ),
                },
            ],
            text_format=GroundedBasis,
        )
        parsed = response.output_parsed
        if parsed is None:
            raise RuntimeError("OpenAI returned no structured grounding for the recommendation.")
        return parsed


# -- Module-level utilities ---------------------------------------------------

def initialize_internal_knowledge_base(
    persist_directory: Path | str = DEFAULT_VECTOR_STORE_DIR,
    *,
    client: OpenAI | None = None,
    embeddings: object | None = None,
) -> Path:
    """Embed and persist all fixed case materials before participant use."""
    load_project_openai_config()
    agent = OpenAIFAISSHiringAgent(
        persist_directory=persist_directory,
        client=client,
        embeddings=embeddings,
    )
    return agent.persist_directory


def create_decision_agent(
    require_live: bool | None = None,
) -> HiringRAGAssistant:
    """Return a live FAISS agent when OpenAI is configured, or the lexical fallback."""
    load_project_openai_config()
    if require_live is None:
        require_live = os.getenv("AGENTIC_REQUIRE_LIVE_RAG", "").lower() in {"1", "true", "yes"}
    if os.getenv("OPENAI_API_KEY"):
        return OpenAIFAISSHiringAgent()
    if require_live:
        raise RuntimeError(
            "AGENTIC_REQUIRE_LIVE_RAG is enabled, but OPENAI_API_KEY is not configured."
        )
    return HiringRAGAssistant()


def is_live_agent(agent: HiringRAGAssistant) -> bool:
    return isinstance(agent, OpenAIFAISSHiringAgent)
